### ISSUE TITLE
Change Ctr-A to other Crt+Alt+A or anything

### ISSUE THREAD

**Issue by HenkDz** [ERROPiX/hydrogen-pack#1]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ERROPiX** [comment]
@HenkDz what's the issue with it now?

Anyway, In the upcoming release, you will be able to change all the shortcuts from the admin settings page

**Comment by ERROPiX** [comment]
Added options to change the shortcuts in 1.0.3
