### ISSUE TITLE
Moving elements up and down with keyboard shortcuts not working anymore. 

### ISSUE THREAD

**Issue by ingenieurbueroalkan** [ERROPiX/hydrogen-pack#11]
Pretty self-explanatory. The shortcut for moving elements up and down are not working anymore. Latest version is installed

**Comment by ingenieurbueroalkan** [comment]
To expand on this, the same goes for ctrl+d for renaming IDs. Also not working properly

**Comment by ERROPiX** [comment]
"ctrl+d" is for duplicate

Anyway, what is your keyboard language and layout?

**Comment by ERROPiX** [comment]
To rename IDs, use ctrl+F2

For the move up and down of elements, it works fine, make sure you select an element that has other elements next to it, if the element selected is the only one in its container, the shortcut will do nothing, it normal

**Comment by ingenieurbueroalkan** [comment]
I'll make a video in a bit.

**Comment by ERROPiX** [comment]
Can't replicate
