### ISSUE TITLE
Block type indication for structure panel

### ISSUE THREAD

**Issue by shock2d** [ERROPiX/hydrogen-pack#13]
First of all! Thanks. The only Oxy addon I really need :)
I like you accurate style of doing thinks. Straightforward and functional.

As hydrogen idea as I understand it is to fix oxygen leak in UX seems like the idea of block type indication fits perfectly into it.

**Describe the solution you'd like**
I like minimal indication and it's not important if it an icon or a color bar and ability to set colors in backend maybe.

**Describe alternatives you've considered**

**Additional context**
webflow way https://i.imgur.com/8RSfDq8.png
alternative way may be like https://i.imgur.com/l1Zt0l4.png

**Comment by ERROPiX** [comment]
I can add this as an option, The issue is that it will take much more from the precious space in that right sidebar.

**Comment by shock2d** [comment]
> I can add this as an option, The issue is that it will take much more from the precious space in that right sidebar.

That's just a suggestion as I found it interesting for plugin. For now I'm going to make an indication for myself using Tampermonkey or some similar chrome addon as after installing hydroned I started renaming blocks (was too lazy before :) ) and now I'm using some special chars like S for sections but it's slower to recognize then color\icon

**Comment by ERROPiX** [comment]
I have found that Oxygen have the icons placeholder for the structure items, it's just not shown, I will add it for future release

**Comment by ERROPiX** [comment]
Added in 1.1.2
