### ISSUE TITLE
Feature Request, Shortcut for selecting parent element

### ISSUE THREAD

**Issue by ingenieurbueroalkan** [ERROPiX/hydrogen-pack#14]
It would be awesome if it would be possible to select the parent element of a given element with a keyboard shortcut. Currently if I'm not missing anything the only way is to click in the top left corner in the oxygen editor

**Comment by ERROPiX** [comment]
Yes, that's a good idea :)

**Comment by ingenieurbueroalkan** [comment]
Awesome that you added it in the new version,
If I may, I have another idea: 
A master keyboard shortcut that opens a list of all available shortcuts inside the editor

**Comment by ERROPiX** [comment]
Yes, I am thinking to add that as well
