### ISSUE TITLE
Copy paste doesnt work after copying a codeblock once

### ISSUE THREAD

**Issue by ingenieurbueroalkan** [ERROPiX/hydrogen-pack#3]
I copied a code block one time and now I can't copy-paste any other oxy element. Every time I paste the code block appears again

**Comment by ERROPiX** [comment]
@ingenieurbueroalkan can you please paste explain what's inside the code block?

**Comment by ingenieurbueroalkan** [comment]
<ul>

**Comment by ingenieurbueroalkan** [comment]
I uploaded a video here on [aws](https://ingenieurbueroalkangmbh.s3.eu-central-1.amazonaws.com/WhatsApp+Video+2020-04-22+at+22.13.05.mp4)

I copied the div but no matter what I do it always pastes the image (the last element I pasted before it stoped working)

**Comment by ingenieurbueroalkan** [comment]
Idk if its related, but I also get the invalid clipboard elements message a lot

**Comment by ERROPiX** [comment]
Ok, I think you are facing the same problems with other on-page that have special characters, can you try the plugin on test page with normal components without the special characters, for example, add a few sections from the design library and test the copy-paste.

An update to fix the encoding issue is coming today to fix that issue.

**Comment by ingenieurbueroalkan** [comment]
That could be the case, on some pages it worked perfectly fine on others not all. I could never find the commonality but the special characters might be it

**Comment by ERROPiX** [comment]
Can you please confirm if the issue has gone after updating to 1.0.3?

**Comment by estraatios** [comment]
It has happened to me also. I changed the language selection to English and it worked

**Comment by ERROPiX** [comment]
@estraatios do you have the latest version 1.0.3?

**Comment by estraatios** [comment]
Yes

Στάλθηκε από το Ταχυδρομείο Yahoo σε Android 
 
  Στις Δευ, 27 Απρ, 2020 στις 4:26 μ.μ., ο χρήστηςAbdelouahed ERROUAGUY<notifications@github.com> έγραψε:   


@estraatios do you have the latest version 1.0.3?

**Comment by ERROPiX** [comment]
Closed for now, as it's due to keyboard layout issues, a reliable shortcuts picker has been added and will be available in next release
