### ISSUE TITLE
add link to your support on your plugin page inside WordPress

### ISSUE THREAD

**Issue by TrustedSamurai** [ERROPiX/hydrogen-pack#4]
Hello,
it was difficult to find your support link.  Can you make it easier with a link to Git from within the Plugin page?  or maybe have a better page for support when the plugin activates?

Thanks.
John.

**Comment by ERROPiX** [comment]
@TrustedSamurai good suggestion, I will add it to the admin page

**Comment by ERROPiX** [comment]
Added in 1.0.3
