### ISSUE TITLE
Not working with Oxygen Builder

### ISSUE THREAD

**Issue by 1EriBa** [ERROPiX/hydrogen-pack#54]
Hi There,

Your plugin doesn’t work on my back-end with Oxygen Builder.

Everything is updated, not many plugins around, I did clean my Cache,…, still nothing.

I get an error, in a red box at the top corner on the left side, telling me:
“Failed to process the clipboard contents
Error: Invalid clipboard contents”

Do you know if I did something wrong, or is it only cause of updates?

Thank you,
Regards,
Eric

**Comment by erropix** [comment]
First, I need to know how you used the copy/paste feature?
If you get that error, it means that the content of your clipboard is not a valid component, maybe you didn't copy the element correctly.
To verify, please paste the content in a text file.

**Comment by 1EriBa** [comment]
Hi ERROPiX,

It looks like I’m doing something not the way I’m supposed to!

Pasting in a text file as you asked, was pasting a text that I copied an hour before ☹

Actually, I’m now asking myself if it’s a Ctrl C + Ctrl V…

Before sending you my request, I have look on Internet, but noting explain, with an example, the way to use your Plugin (post, websites or videos).

Do I have to paste an element another way?

Regards,
Eric

**Comment by erropix** [comment]
The issue then is in the copy method, you first need to activate the element you need to copy, then either use the right click menu to copy, or use the shortcut ctrl+c (cmd+c for Mac) you should see a flashing animation if the copy is successful.

To paste the copied elements, you just need to use ctrl+v (cmd+v for Mac) or any other shortcuts you normally use as it also work with clipboard managers.

**Comment by 1EriBa** [comment]
Here is the problem…
I have no special menu  on the right click, just the classic one from Chrome.
Why is that?

(same on Firefox)

**Comment by erropix** [comment]
Ok, this need to be resolved privately via email, please send a temporary login details to support@cleanplugins.com

**Comment by 1EriBa** [comment]
I have send you an email with a temporary login link :)

**Comment by 1EriBa** [comment]
It was my mistake; I mixed up Hydrogen Paste and Hydrogen Pack.
Thank you for your support :)
Regards,
Eric
