### ISSUE TITLE
Cross site copy paste not working

### ISSUE THREAD

**Issue by ingenieurbueroalkan** [ERROPiX/hydrogen-pack#6]
When trying to copy header builder element between different sites I get the following error: 

Uncaught TypeError: _.findWhere is not a function on line #13 in https://hamam.snicco.de/wp-content/plugins/oxygen/component-framework/angular/controllers/iframe.min.js?ver=3.2.1

**Comment by ERROPiX** [comment]
Do this happen on all sites or just one of your sites? are both sites using the same version?

**Comment by ingenieurbueroalkan** [comment]
Currently only having oxygen on 2 sites so I dont know about that, but yes same version

**Comment by ERROPiX** [comment]
ok, can you send me the copied code via the support form here so I can try it?
https://www.erropix.com/support/

**Comment by estraatios** [comment]
try with the English language selected and with the keyboard shortcuts only. It worked for me
