### ISSUE TITLE
Conditions window height

### ISSUE THREAD

**Issue by estraatios** [ERROPiX/hydrogen-pack#8]
Hi

When I try to add a new condition and click the "Add your first condition button" the height of the windows is way too small. So when I click the "Choose condition" I have very little space to scroll.

![hydro](https://user-images.githubusercontent.com/34076187/80342029-26fa3a00-886c-11ea-8cd4-89bc3eb8deea.PNG)

**Comment by ERROPiX** [comment]
Thank you for reporting this, it has been fixed locally after someone else reported it.

**Comment by estraatios** [comment]
Ok. Thanks.

I will create a youtube tutorial video about this plugin. Can you please tell me what features do you plan to add first? I mean in the next 1-2 months?

Thanks

**Comment by ERROPiX** [comment]
Thanks for doing this, there will copy styles, and enhanced classes management, 
The biggest one will be Hydrogen Sandbox currently under development, here is an early preview https://www.loom.com/share/49b8fd670e6f40109e88f0df37ab0661

**Comment by estraatios** [comment]
That's awesome. So the logged out users will not see the changes until the page is ready, right? You should add roles to that so we can choose if we want only the admins to see the changes.

Also if you can, Autosave, Undo - Redo, and relative size fonts (or global size for breakpoints) would be great.

**Comment by ERROPiX** [comment]
Yes, that's how it will work, here is the Facebook post and discussion about it https://web.facebook.com/groups/1626639680763454/permalink/2908067222620687/

**Comment by estraatios** [comment]
I have made the review video. You can see it here https://youtu.be/XoERpZmTFj0
It will be public at the end of this week. Any comments would be appreciated.

**Comment by estraatios** [comment]
Did you have any time to check the video?

**Comment by ERROPiX** [comment]
Hi,

I forgot it, but I am checking it now, I will let you know my feedback :)

Thanks

**Comment by ERROPiX** [comment]
Hi,

That's a good video, all the details are correct and well explained, except
for one thing. You can use the "copy" menu item for cross sites, but not
the "paste" this is due to privacy restriction by the browser, we can't
access the clipboard content without the user pasting it (using system
shortcut or clipboard manager), if you think about it. if all websites can
read your clipboard, then your private data will be stolen.

Anyway, thank you so much for the effort you did in making this video

**Comment by estraatios** [comment]
Oh, did not know that. I will correct that before publishing it.

**Comment by ERROPiX** [comment]
fixed in 1.1.0
