### ISSUE TITLE
Copy and Paste Icons

### ISSUE THREAD

**Issue by estraatios** [ERROPiX/hydrogen-pack#9]
When you copy and paste icons from another website the icon itself is not selected. So it will copy the element with the styling but with no actual icon selected and you will have to go and choose the icon.

Inside the same page, it works normally

Tested with version 1.0.3

**Comment by ERROPiX** [comment]
Do both site have the same icon set installed?

**Comment by estraatios** [comment]
Oh! You are absolutely right. My mistake.

Sorry!
